// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Button.tsx": () => import("../components/mockups/Button.tsx"),
  "./components/mockups/Card.tsx": () => import("../components/mockups/Card.tsx"),
  "./components/mockups/Form.tsx": () => import("../components/mockups/Form.tsx"),
  "./components/mockups/navigation/Navbar.tsx": () => import("../components/mockups/navigation/Navbar.tsx")
};
